{
  config,
  pkgs,
  inputs,
  ...
}: {
  environment.systemPackages = with pkgs; [
    wget
    alejandra
    (python3Full.override {
      enableOptimizations = true;
      reproducibleBuild = false;
    })
    nodePackages_latest.nodejs
    gimp
    gcc
    llvmPackages.libcxxClang
    typora
    telegram-desktop
    libreoffice-qt
    hunspell
    hunspellDicts.es_ES
    hunspellDicts.en_US
    onlyoffice-bin
    blender
    chromium
    discord
    tor-browser
    vlc
    kdePackages.kate
    kdePackages.kdenlive
    kdePackages.yakuake
    kdePackages.filelight
    kdePackages.kalk
    kdePackages.kfind
    htop
    wineWowPackages.stable
    ncdu
    vdhcoapp
    (rust-bin.stable.latest.default.override {
      extensions = ["rust-src"];
    })
    pcmanfm
    neofetch
    calibre
    inputs.nix-software-center.packages.${system}.nix-software-center
    squashfsTools
    obs-studio
    teams-for-linux
    lm_sensors
    pciutils
    iw
    inxi
    lshw
    docker-compose
    file
    inputs.nix-alien.packages.${system}.nix-alien
    config.boot.kernelPackages.perf
    appimage-run
    lz4
    p7zip
    lsof
    zip
    dolphin-emu-primehack
    mold
    unrar
    ghidra-bin
    mame-tools
    freetube
    stremio
    orca-slicer
    gittyup
    mgba
    gh
    nixpkgs-review
    postman
    nvidia-container-toolkit
    emulationstation-de
    transmission_4-qt6
    libjxl
    ntfs3g
    exiftool
  ];
}
